spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-aiguigu-dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-aiguigu-test